name: Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  format_compile_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: VirtusLab/scala-cli-setup@v0.2.1
        with:
          jvm: adopt:11
      - name: Check format
        run: sbt checkFormat
      - name: Scalafix Lint
        run: sbt scalafixLint
      - name: Scapegoat Lint
        run: sbt scapegoatLint
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: VirtusLab/scala-cli-setup@v0.2.1
        with:
          jvm: adopt:11
      - name: Run tests with coverage Report
        run: sbt testCoverage
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
